#version 440
#extension GL_GOOGLE_include_directive : require
layout(location = 0) in vec2 qt_TexCoord0;
layout(location = 0) out vec4 fragColor;
layout(std140, binding = 0) uniform buf {
    mat4 qt_Matrix;
    float qt_Opacity;
    vec2 resolution;
    float phaseTime;
    float fixtureMode;
    float fixtureLinear;
    float fixtureOrder;
    vec2 testSource;
#define BH_UNIFORMS
#include "blackhole.glsl"
#undef BH_UNIFORMS
} ubuf;
#include "blackhole.glsl"
// Optional labelled source grid, generated by the probe. Production uses no
// background texture: it evaluates its equal-area star grid at the warped point.
layout(binding = 4) uniform sampler2D fixtureGrid;

vec3 fixtureStars(vec2 pixel) {
    vec2 c = floor(pixel/52.0);
    vec2 jitter = fract(sin(vec2(dot(c,vec2(127.1,311.7)),dot(c,vec2(269.5,183.3))))*43758.5453);
    vec2 d = pixel-(c+0.15+0.7*jitter)*52.0;
    float d2 = dot(d,d);
    if (d2 > 16.0) return vec3(0.0);
    return vec3(0.13,0.15,0.18)*exp(-d2/1.6)*(1.0-bhEase((d2-4.0)/12.0));
}
void main() {
    vec2 pixel = qt_TexCoord0*ubuf.resolution;
    float mode = ubuf.fixtureMode;
    if (mode >= 21.0) {
        float side = pixel.x < ubuf.resolution.x*0.5 ? -1.0 : 1.0;
        float radius = mode < 22.0 ? ubuf.testSource.x+side*ubuf.testSource.y : 4.0;
        float phi = mode < 22.0 ? 0.73 : side*BH_PI+ubuf.testSource.y;
        if (mode >= 23.0) {
            radius = mix(ubuf.bhDisk.x,bhOuter(),pixel.y/ubuf.resolution.y);
            phi = (pixel.x/ubuf.resolution.x*2.0-1.0)*BH_PI;
        }
        fragColor = vec4(vec3(bhFilaments(radius,phi,vec2(0.00001),ubuf.bhDetail.w)*0.1),1.0);
        return;
    }
    if (mode >= 14.0) {
        vec2 p = pixel-ubuf.bhCentre;
        float r = length(p);
        vec2 e = p/max(r,0.0001);
        vec4 hit = bhCrossing(bhColumn(bhImpact(r)),e,ubuf.fixtureOrder);
        if (mode < 15.0 || mode >= 19.0)
            hit = vec4(mix(ubuf.bhDisk.x,bhOuter(),pixel.y/ubuf.resolution.y),
                (pixel.x/ubuf.resolution.x*2.0-1.0)*BH_PI,1.0,0.0);
        vec2 footprint = bhFootprint(hit);
        vec3 colour;
        if (mode < 15.0) colour = bhShadeField(hit,e,BH_BC,footprint,ubuf.bhDetail.w,1.0)*bhEdge(hit.x);
        else if (mode < 16.0) colour = bhEmissionAt(hit,e,ubuf.fixtureOrder,bhImpact(r),footprint).rgb;
        else if (mode < 17.0) colour = vec3(bhDiskAbsorb(pixel));
        else if (mode < 18.0 || mode >= 20.0) {
            vec2 knot = bhKnot(hit.x,hit.y,footprint);
            colour = vec3(knot.x,knot.y/768.0,hit.z*bhEdge(hit.x));
        } else {
            vec2 ember = bhEmber(hit.x,hit.y,footprint);
            colour = vec3(ember.x,ember.y/32.0,hit.z*bhEdge(hit.x));
        }
        if (ubuf.fixtureLinear < 0.5) colour = mix(12.92*colour,1.055*pow(max(colour,vec3(0.0)),vec3(1.0/2.4))-0.055,step(vec3(0.0031308),colour));
        fragColor = vec4(colour,1.0);
        return;
    }
    if (mode > 8.5 && mode < 9.5) {
        float word = bhWord(vec2(mod(floor(pixel.x),8.0),260.0))*65535.0;
        fragColor = vec4(floor(word/256.0)/255.0,mod(word,256.0)/255.0,0.0,1.0);
        return;
    }
    vec2 p = pixel-ubuf.bhCentre;
    float r = length(p);
    if (mode > 12.5 && mode < 13.5) {
        float az = pixel.x < ubuf.resolution.x*0.5 ? -BH_PI : BH_PI;
        fragColor = bhEmission(vec4(4.0,az,1.0,2.0),vec2(0.2,-0.98),0.0);
        return;
    }
    if (mode > 11.5 && mode < 12.5) {
        mat2 j = bhJacobian(pixel);
        fragColor = vec4(j[0],j[1]);
        return;
    }
    if (mode >= 7.0 && mode < 9.0) {
        float extra;
        vec2 mapped = mode < 8.0 ? bhWarpBackground(pixel,extra) : bhWarpMaterial(pixel,extra);
        fragColor = vec4(mapped/ubuf.resolution,extra,bhShadowMask(pixel));
        return;
    }
    if (mode >= 5.0 && mode < 7.0) {
        vec4 hit = bhCrossing(bhColumn(bhImpact(r)),p/max(r,0.0001),floor(mode-5.0));
        float a = hit.z*step(r,ubuf.bhGeometry.y);
        fragColor = vec4(vec3((hit.x-3.0)/5.0,0.5+0.5*cos(hit.y),0.5+0.5*sin(hit.y))*a,a);
        return;
    }
    float weight;
    vec2 source = bhWarpBackground(pixel,weight);
    vec3 background = vec3(0.0);
    if (mode < 0.5 || mode > 9.5) background = fixtureStars(source);
    if (mode > 1.5 && mode < 3.5) {
        vec2 d = source-ubuf.bhCentre-ubuf.testSource;
        float d2 = dot(d,d);
        background = vec3(0.06,0.18,0.24)*exp(-d2/18.0)*(1.0-bhEase((d2-36.0)/108.0));
    }
    if (mode > 3.5 && mode < 4.5) {
        vec2 uv = source/ubuf.resolution;
        if (uv.x >= 0.0 && uv.y >= 0.0 && uv.x <= 1.0 && uv.y <= 1.0)
            background = texture(fixtureGrid,uv).rgb;
    }
    background *= 1.0-bhShadowMask(pixel);
    if (mode > 9.5) {
        float rimLife;
        vec2 material = bhWarpMaterial(pixel,rimLife)-ubuf.bhCentre;
        float radius = max(0.0,240.0-ubuf.phaseTime*12.0);
        vec2 d = material-vec2(radius,0.0);
        float rh = ubuf.bhGeometry.x;
        float candidateLife = smoothstep(rh,1.08*rh,sqrt(radius*radius+rh*rh));
        background += vec3(0.18,0.22,0.25)*exp(-dot(d,d)/6.0)*rimLife*candidateLife*step(dot(d,d),100.0);
    }
    vec4 disk = vec4(0.0);
    if (mode < 1.5 || mode > 9.5) disk = bhDisk(pixel);
    vec3 linearColour = background*(1.0-disk.a)+disk.rgb;
    // Raw EGL measurements request linear output; QtQuick presentation encodes
    // once for its ordinary display surface. All caps apply before this step.
    if (ubuf.fixtureLinear < 0.5 && dot(linearColour,linearColour) > 0.0)
        linearColour = mix(12.92*linearColour,1.055*pow(max(linearColour,vec3(0.0)),vec3(1.0/2.4))-0.055,step(vec3(0.0031308),linearColour));
    fragColor = vec4(linearColour,1.0)*ubuf.qt_Opacity;
}
